### ISSUE TITLE
Sketch for the SSD1306 (ESP8266)

### ISSUE THREAD

**Issue by MagTun** [jandelgado/NodeMCU#1]
Hi

Thanks for sharing the connections for the [ESP8266](https://github.com/jandelgado/NodeMCU/wiki/SSD1306-based-OLED-connected-to-ESP8266), it's really not easy to find it for this version of the OLED SSD12306!

You didn't add a sketch with the connections but you mention that we should use the u8g2 library. I have seen that you shared [sketches for arduino](https://github.com/jandelgado/arduino/wiki/SSD1306-based-OLED-connected-to-Arduino) but I couldn't find the one made with u8g2  only u8g. Can I use this one instead? If not, do you still have a working sketch for ESP8566?

Thanks for your help!

**Comment by MagTun** [comment]
I ended up following this [tuto](https://www.instructables.com/id/Wemos-D1-Mini-096-SSD1306-OLED-Display-Using-SPI/)

**Comment by jandelgado** [comment]
Excellent - thanks for the Info
